### ISSUE TITLE
Webinterface fails if the a share gets removed.

### ISSUE THREAD

**Issue by patricks** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#19] opened 2018-01-24 07:53 UTC
I did the following in the web-ui

- Create a job and selected a "backup-share"
- Removed this share later in the web-ui

After that the web-ui of rsnapshot, doesn't show anything because it can't load the config. I had to remove the <job> manually in the config.xml to get it working again.

**Comment by ryecoaaron** [comment] 2018-01-24 19:29
The problem is the plugin doesnt have the shared folder references named correctly.  So, the shared folder doesn't show up as referenced which would prevent you from deleting the shared folder.  Until I have a chance to fix this, you should use the shared folder in use tab to determine if a shared folder in referenced before deleting anything.

**Comment by ryecoaaron** [comment] 2018-08-16 16:42
Fixed in commit https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot/commit/a848e1c2f985a488e196e160c7a5f5b5818bf5a1

**Closed by ryecoaaron** 2018-08-16 16:42 UTC
