### ISSUE TITLE
Support for remote backup

### ISSUE THREAD

**Issue by fumantsu** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#27] opened 2020-02-17 13:41 UTC
Since I didn't see someone to ask it, I will give a try.
I see that rsnapshot supports remote backups since is based on rsync. Since OMV has already implement remote rsync why not rsnapshot do the same instead of be limited between shared folders.
I'm sure that people are already using hybrid solutions which.... take space, time etc.

**Comment by ryecoaaron** [comment] 2020-02-17 14:31
It would be nice but there is a difference.  rsnapshot only supports pulling from remote sources.  I've look at it but there is a ton of code to rewrite.  For me, I just rsync to second server and then have rsnapshot setup on the other server.  Sure this is a second copy but I consider that a good thing. 
 Someone will have to do this if it is wanted.

**Comment by fumantsu** [comment] 2020-02-17 15:02
I'm talking about pulling as I trying to keep a small backup from some devices with one "hot" disk and one "cold", so I was planning to keep backup in the cold but only there and when it is active the disk. Anyway, if someone have the time, it would be nice.

btw: I didn't know that you were also write this plugin. I bother you a lot today :D

**Comment by Eurbaix** [comment] 2020-03-16 03:22
@fumantsu You can do a remote backup by using the Remote Mount plugin to mount a remote share, then create a sharedfolder on the Remote Mount "file system". In my experience, the performance is not too bad on a SMB/CIFS remote mount (about 25-30% of the ideal rsync client to rsync server) but, surprisingly, it's abysmal on an NFS remote mount, which I expected would have better performance than SMB/CIFS (maybe it's just my setup, you should compare NFS vs SMB/CIFS remote mount performance yourself).

@ryecoaaron What would really make a difference is to support rsync servers. Rsync is 3 to 5 times faster (and therefore Rsnapshot) when the target is an rsync server, compared to a simple network share. I believe this could be done mostly by adding code (instead of rewriting it, which is always a nightmare) if the interface has two different "Add" buttons. Then, the code could remain the same for adding a Sharedfolder to Sharedfolder rsnapshot and only new code would be needed (with just a bit of rewriting to implement the second "Add" button. It would still need quite a bit of code but, at least, the existing code could remain mostly untouched.

**Comment by ryecoaaron** [comment] 2020-03-16 12:20
@Eurbaix feel free to submit a pull request.  As I mentioned above, I have looked into this before and it would require a large code rewrite to eliminate code duplication that I don't have time for.

I use this plugin myself but I use rsync between servers with rsnapshot local on both ends.  Yes, it uses double the space on each end but that is extra backup to me.

**Comment by Eurbaix** [comment] 2020-03-16 13:05
> I use this plugin myself but I use rsync between servers with rsnapshot local on both ends. Yes, it uses double the space on each end but that is extra backup to me.

Doubling the number of disks on both the backup and main NAS is not exactly something my bank account looks forward to ;-). I'll stay with the remote mount for now even if it's slower than rsync client to rsync server.

> feel free to submit a pull request. 
As I mentionned in another issue, my programming skills are really rusted (and quite obsolete) so I may do more damage than good. Maybe one day, when I've derusted my programming enough, which I'm working on.

**Comment by Eurbaix** [comment] 2020-03-16 22:25
Could you change the title of the issue to "Support for rsync server". Support for remote backup is solved, since you can use the Remote Mount plugin. If the title of the issue is more accurate, there is more chance someone with more experience than me can chime in and develop a solution.

Or we can close this issue and reopen a new one about rsync server, that you label for later, so people are aware that this is not coming soon. Your choice.

**Comment by ryecoaaron** [comment] 2024-02-18 23:20
closing due to age.

**Closed by ryecoaaron** 2024-02-18 23:20 UTC
